package util;

import java.sql.Connection;
import java.sql.SQLException;
import java.sql.Statement;

public class LoadTables {

	public void creatScherma(Connection c) throws SQLException {
		
		
		Statement stmt = c.createStatement();
		
		
	 stmt.execute("CREATE TABLE IF NOT EXISTS PRODUTOS ("
	 		+ " PRODUTOS_ID SERIAL PRIMARY KEY,"
	 		+ " PRODUTOS_IDENTIFICACAO VARCHAR(255),"
	 		+ "FRANQUIA_ID INTEGER,"
	 		+ "TIPO_ID INTEGER );");
			 
			stmt.execute("CREATE TABLE IF NOT EXISTS CLIENTES ("
					+ "CLIENTES_ID Serial PRIMARY KEY,"
					+ "CLIENTES_NOME VARCHAR(255),"
					+ "CLIENTES_CPF  VARCHAR(255),"
					+ "CLIENTES_TELEFONE VARCHAR(255),"
					+ "CLIENTES_ENDERECO VARCHAR(255),"
					+ "CLIENTES_DESCRICAO VARCHAR(255) );");
			    
			stmt.execute("CREATE TABLE IF NOT EXISTS FRANQUIAS ("
					+ "FRANQUIAS_ID SERIAL PRIMARY KEY,"
					+ "FRANQUIAS_NOME VARCHAR(255),"
					+ "LOCAL VARCHAR(255),"
					+ "FRANQUIAS_HORA_FUN TIME,"
					+ "FRANQUEADO_ID  INTEGER);");
					
			 stmt.execute("ALTER TABLE PRODUTOS "
			 		+ "ADD FOREIGN KEY (FRANQUIA_ID) "
			 		+ "REFERENCES FRANQUIAS(FRANQUIAS_ID);");
				
			stmt.execute("CREATE TABLE IF NOT EXISTS TIPOS ("
					+ "TIPOS_ID SERIAL PRIMARY KEY,"
					+ "TIPOS_NOME VARCHAR(255),"
					+ "TIPOS_DESCRICAO VARCHAR(255));");
					
			stmt.execute("ALTER TABLE PRODUTOS "
					+ "ADD FOREIGN KEY (TIPO_ID)"
					+ " REFERENCES TIPOS(TIPOS_ID);");

			stmt.execute("CREATE TABLE IF NOT EXISTS USUARIOS ("
					+ "USUARIOS_ID SERIAL  PRIMARY KEY,"
					+ "USUARIOS_LOGIN VARCHAR(255) UNIQUE,"
					+ "USUARIOS_SENHA VARCHAR(255),"
					+ "FRANQUEADO_ID INTEGER UNIQUE,"
					+ "USUARIOS_FUNCAO INTEGER,"
					+ "USUARIOS_FOTO BYTEA  );");

			stmt.execute("CREATE TABLE IF NOT EXISTS RESERVAS ("
					+ "RESERVAS_ID SERIAL PRIMARY KEY,"
					+ "RESERVAS_QTD_PESSOAS VARCHAR(255),"
					+ "RESERVAS_DESCRICAO  VARCHAR(255),"
					+ "RESERVAS_DATA DATE,"
					+ "RESERVAS_HORA_INICIO TIME,"
					+ "RESERVAS_HORA_FIM TIME,"
					+ "MESA_ID INTEGER,"
					+ "CLIENTE_ID INTEGER);");
			    
			stmt.execute("ALTER TABLE RESERVAS "
					+ "ADD FOREIGN KEY (MESA_ID) "
					+ "REFERENCES PRODUTOS(PRODUTOS_ID);");

			stmt.execute("ALTER TABLE RESERVAS"
					+ " ADD FOREIGN KEY (CLIENTE_ID)"
					+ " REFERENCES CLIENTES(CLIENTES_ID);");

			stmt.execute("CREATE TABLE IF NOT EXISTS FRANQUEADOS ("
					+ "FRANQUEADOS_ID INTEGER PRIMARY KEY,"
					+ "FRANQUEADOS_NOME VARCHAR(255),"
					+ "FRANQUEADOS_SOBRENOME VARCHAR(255),"
					+ "FRANQUEADOS_DATANASCIMENTO VARCHAR(255),"
					+ "FRANQUEADOS_CPF VARCHAR(255),"
					+ "FRANQUEADOS_CELULAR VARCHAR(255),"
					+ "FRANQUEADOS_FONERESIDENCIA VARCHAR(255),"
					+ "FRANQUEADOS_FONECOMECIAL VARCHAR(255),"
					+ "FRANQUEADOS_ENDERECO VARCHAR(255),"
					+ "FRANQUEADOS_BAIRRO VARCHAR(255),"
					+ "FRANQUEADOS_CEP VARCHAR(255),"
					+ "FRANQUEADOS_CIDADE VARCHAR(255),"
					+ "FRANQUEADOS_ESTADO VARCHAR(255),"
					+ "FRANQUEADOS_EMAIL VARCHAR(255) UNIQUE);");
				
			stmt.execute("ALTER TABLE FRANQUIAS"
					+ " ADD FOREIGN KEY (FRANQUEADO_ID)	"
					+ "REFERENCES FRANQUEADOS(FRANQUEADOS_ID);");

			stmt.execute("ALTER TABLE USUARIOS"
					+ " ADD FOREIGN KEY (FRANQUEADO_ID) "
					+ "REFERENCES FRANQUEADOS(FRANQUEADOS_ID);");

			stmt.execute("INSERT INTO USUARIOS ("
					+ "USUARIOS_LOGIN,"
					+ "USUARIOS_SENHA,"
					+ "USUARIOS_FUNCAO) "
					+ "VALUES ('admin','123',2);");
				
	}
}
